### ISSUE TITLE
Improve scanning on random option

### ISSUE THREAD

**Issue by domineaf** [Mizogg/Tkinter-Power#1]
Hi **Mizogg**, I have an idea that I think will improve the random scanning result, I want to see if you can implement it .

Is it possible that in random mode when scanning a page or range can save the info that already scanned that range or specific page to not scan redundantly again? can be in a file where the progress is saved may be on a local database but each page range scanned, but always keeping the random mode not sequential, that will make each time we are closer to find a specific private key randomly because the range to scan will decrease more and more, Is this possible, I would like that you can implement it, Let me know, Thanks.

**Comment by Mizogg** [comment]
Hi Domineaf,
It is not possible to save all random scan results. the file would become very large. With the sequence way it records the last place scanned and will begin from that location. The random will also use the Sequence last location so at least the range will become smaller while scanning random.
