### ISSUE TITLE
Total BTC addresses loaded and checking 160.

### ISSUE THREAD

**Issue by Laululytia** [Mizogg/Tkinter-Power#2]
I can see your program has much more. Doesn't matter how many I put in btc.bf file still same amount on the main window

**Comment by Mizogg** [comment]
You need to create your one database.. In the files folder has a test btc.txt and Cbloom.py which makes the bloom filter database. The Tkinter program Bitcoinhunter needs this database to be  in the top folder. Currently is called puzzle.bf. Replace the puzzle.bf with your database then you will have more that 160 Addresses.
