### ISSUE TITLE
eth1.bf

### ISSUE THREAD

**Issue by Tfoutu** [Mizogg/Tkinter-Power#5]
hello why does it need two files eth.bf and eth1.bf?

**Comment by Mizogg** [comment]
I have removed that so it only requires one eth.bf file. Please check the new update

**Comment by Tfoutu** [comment]
Thanks a lot ! I have tested a lot of hunting scripts, and i think, yours are the best.

**Comment by Tfoutu** [comment]
You can count on me for a contribution to your time spent programming when I will find something.
